spring:
  application:
    name: StarForest

  mail:
    host: smtp.gmail.com
    port: 587
    username: bosco960227
    password: yfoirvehsaduwtrg
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://starforest.cng4woomu8oy.ap-northeast-2.rds.amazonaws.com:3306/starforest_back?useSSL=false&serverTimezone=UTC
    username: admin
    password: admin1234
    hikari:
      maximum-pool-size: 5

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
        dialect.storage_engine: innodb
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

server:
  port: 8080

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

com:
  study:
    spring:
      upload:
        path: upload

file:
  upload-dir: src/main/resources/static/uploads

app:
  image:
    base-url: http://localhost:8080/uploads/

cloud:
  aws:
    credentials:
      accessKey: AKIA47CR3UK7AQEQT5OA
      secretKey: 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
    s3:
      bucket: startforest
    region:
      static: ap-northeast-2
    stack:
      auto: false

kakao:
  admin:
    key: 7f9845b2242e0a32f44fe8c9db5d1b6b
